dist: bionic
language: generic

services:
  - docker

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    # DOCKER_USERNAME is set in travis UI.
    # DOCKER_PASSWORD is set in travis UI.
  matrix:
    - TARGET_ARCH=armhf
    - TARGET_ARCH=aarch64

# The following is needed for Docker builds (buildkit support)
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - export GIT_SHA=$(git rev-parse --short $TRAVIS_BRANCH)

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - travis_wait 60 docker build --no-cache --pull -t dwelo2/rust-musl-crosscompiler:${TARGET_ARCH} --build-arg TARGET_ARCH=${TARGET_ARCH} .

# after_script:
#   - docker push dwelo2/rust-musl-crosscompiler:${TARGET_ARCH}
