#!/usr/bin/env bash
# Builds a deb package of boss for armhf.
# Must be run from the root of the repo, inside the builder container.

set -euo pipefail

# Append -BOSS_GIT_VERSION (e.g. "-master-0123abc") to the package version in Cargo.toml
sed -ie "s/^\(version = \".*\)\"\$/\1-$BOSS_GIT_VERSION\"/" Cargo.toml

# Fetch crates so that we have a zware_rs crate available before the build
cargo fetch --target=armv7-unknown-linux-gnueabihf

# Extract the latest 'zwave_device_rec.txt' from the zware_rs crate so we can ship it in the deb.
cp -f $(find ${HOME}/.cargo/git/checkouts/zware_rs* -iname zwave_device_rec.txt | head -n1) ./zwave_device_rec.txt

# Make the deb!
cargo deb --target=armv7-unknown-linux-gnueabihf --no-strip -- --all-features

# Cleanliness is valued.
rm -f ./zwave_device_rec.txt

# Write the boss version string out to a file that we can eventually copy into the balena-boss-runtime repo
echo $(awk -F "=" '/^version/ {print $2}' Cargo.toml | tr -d '"' | tr -d ' ') > target/armv7-unknown-linux-gnueabihf/debian/boss_package_version.txt
