#!/usr/bin/env bash
# Builds a tgz package of boss for TARGET_ARCH.
# Must be run from the root of the repo, inside the builder container.

set -euo pipefail

# get the version string from Cargo.toml
boss_version=$(awk -F "=" '/^version/ {print $2}' Cargo.toml | tr -d '"' | tr -d ' ')

# Append +BOSS_GIT_VERSION (e.g. "+master-0123abc") to the Cargo.toml version
boss_package_version="${boss_version}+${BOSS_GIT_VERSION}"

# Extract the latest 'zwave_device_rec.txt' from the zware_rs crate so we can ship it in the deb.
zwave_rec_path=$(find ${HOME}/.cargo/git/checkouts/zware_rs* -iname zwave_device_rec.txt | head -n1)

rm -rf deploy
mkdir -p deploy

# Make the tgz!
# boss_0.6.1+master-240ee46_armhf.deb
tar cfzv "deploy/${boss_package_version}_${TARGET_ARCH}.tar.gz" --transform 's!^.*/!!' "${zwave_rec_path}" "target/${RUST_TARGET}/release/boss"

# Write the boss version string out to a file that we can eventually copy into the balena-boss-runtime repo
echo "${TRAVIS_BRANCH}/${boss_package_version}_${TARGET_ARCH}.tar.gz" > "target/boss_package_version.txt"
