[build]
# Target musl by default when running Cargo.
target = "armv7-unknown-linux-musleabihf"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-gcc"
ar = "arm-linux-musleabihf-ar"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
ar = "aarch64-linux-musl-ar"
